


```{r}
library(tidyverse)
library(corrplot)

```

```{r}

data.combine<-read.csv("./ProcessedData/combine.csv")
data.coal<-read.csv("./ProcessedData/HC_Coal_Edit.csv")

```

#Select out 2019 data and remove counties with 0s for white population. Join new coal data (no year - just year of max production and total sum production) to acs and health data. 
```{r}

data.edit<-data.combine %>% 
  filter(year==2019) %>% 
  filter(perc.white!=0) %>% 
  select(!c(1,coal.prod.by.year, year.peak.prod, sum.coal.prod))


data.coal.clean<-data.coal %>% 
  select(!1) %>% 
  mutate(year.from.peak.2019=2019-year.peak.prod)

data.coal.health.acs<-full_join(data.edit, data.coal.clean, by="County")

```

#run MLR
```{r}

acs.coal.health.regression <- lm(data = data.coal.health.acs, Health.Outcomes.Z.Score ~ totpop + medage + medincome + perc.white +  perc.bachdegree + year.from.peak.2019 + sum.coal.prod)
summary(acs.coal.health.regression)

#Choose a model by AIC in a Stepwise Algorithm
step(acs.coal.health.regression)

acs.coal.health.regression.2<-lm(data = data.coal.health.acs, Health.Outcomes.Z.Score ~ medage + perc.white + 
    perc.bachdegree + year.from.peak.2019)
summary(acs.coal.health.regression.2)

```

#Check MLR assumptions
```{r}

par(mfrow = c(2,2), mar=c(4,4,4,4))
plot(acs.coal.health.regression.2)
par(mfrow = c(1,1))

#remove county and other non-informative variables to permit correlation plot
acs.health.coal.cor.edit <- data.coal.health.acs %>% 
  select(!c(County,totpop,totpoprace, totpopeduc, totpopwhite, bachdegree,Health.Factors.Z.Score,
            Health.Factors.Rank, year.peak.prod, year)) %>% 
  na.omit()



acs.health.coal.Corr <- cor(acs.health.coal.cor.edit)
corrplot(acs.health.coal.Corr, method = "circle", type="upper")
corrplot.mixed(acs.health.coal.Corr, upper = "circle")


```

