




```{r Installing and loading packages}
library(lubridate)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(readxl)
library(imputeTS)
library(trend)
library(zoo)
library(Kendall)
library(tseries)
library(latticeExtra)
```


##Analyzing the Data Over Time
When examined in conjunction with each other, there is data spanning 1989 to 2002


```{r data wrangling}

full.data <- read.csv("ProcessedData/combine.csv")
full.data$year <- sort(full.data$year)

health.data <- read.csv("ProcessedData/healthdf.csv")

health.data <- health.data %>%
  rename("Year" = "year")

actual.full.data <- merge(health.data, aggCoalSlim, by = c("County", "Year")) %>%
  select(Year, County, Health.Outcomes.Z.Score, Health.Factors.Z.Score, sum.coal.production)

#end of good

195-593

full.data2 <- full.data[195:593, ]

slim.data <- select(full.data2, c("County", "medincome", "perc.bachdegree", "medage", "year", "coal.prod.by.year", "Health.Outcomes.Z.Score", "Health.Factors.Z.Score"))

slim.data[is.na(slim.data)] <- 0

slim.data$year <- as.Date(as.character(slim.data$year), format = "%Y")
  

data.coal <- filter(slim.data, coal.prod.by.year != 0)

data.no.coal <- filter(slim.data, coal.prod.by.year == 0)

data.no.coal2 <- data.no.coal %>%
  group_by(year) %>%
  mean(medincome, perc.bachdegree, Health.Outcomes.Z.Score, Health.Factors.Z.Score)

ggplot(data.no.coal, aes(x = year, y = Health.Outcomes.Z.Score))+
  geom_point()+
  geom_smooth()

data.no.coal2 <- data.no.coal[, -1]

data.no.coal <- data.no.coal2 %>%
  group_by(year) %>%
  summarise(across(everything(), mean),
            .groups = 'drop')  %>%
  as.data.frame()

schuylkill.data <- filter(actual.full.data, actual.full.data$County == "Schuylkill")


ggplot(schuylkill.data, aes(x=year, y=Health.Factors.Z.Score))+
  geom_line()

x <- data.frame(Year = c(2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020))

#fixed one!
#comparing health factor z score with coal production in schuylkill county
Year <- schuylkill.data$year
var1<- schuylkill.data$Health.Factors.Z.Score
var2 <- schuylkill.data$sum.coal.production
data <- data.frame(x,var1,var2)

obj1 <- xyplot(var1 ~ Year, data, type = "l" , lwd=2, col="steelblue", ylab = "Health Factors Z Score (Blue)", col.axis = "red")
obj2 <- xyplot(var2 ~ Year, data, type = "l", lwd=2, col="red", ylab = "Coal Produced in Tons (Red)")

doubleYScale(obj1, obj2, add.ylab2 = TRUE, use.style=FALSE)

#comparing health outcomes z score in schuylkill county
Year <- schuylkill.data$year
var1<- schuylkill.data$Health.Outcomes.Z.Score
var2 <- schuylkill.data$coal.prod.by.year
data <- data.frame(x,var1,var2)

obj1 <- xyplot(var1 ~ Year, data, type = "l" , lwd=2, col="steelblue", ylab = "Health Outcomes Z Score (Blue)", col.axis = "red")
obj2 <- xyplot(var2 ~ Year, data, type = "l", lwd=2, col="red", ylab = "Coal Produced in Tons (Red)")

doubleYScale(obj1, obj2, add.ylab2 = TRUE, use.style=FALSE)

#trend in health outcomes across all non-coal producing counties

data.no.coal$County <- as.factor(data.no.coal$County)

ggplot()+
  geom_smooth(x = data.no.coal$year, y = data.no.coal$Health.Outcomes.Z.Score)



time.series.correlation <- MannKendall(schuylkill.data)

summarise(time.series.correlation)

```





```{r}

data.ts <- ts(data.no.coal$Health.Outcomes.Z.Score, start = c(1989, 12), frequency = 1)

coal.data.decomp <- stl(data.ts)

plot(coal.data.decomp)

data.trend1 <- Kendall::MannKendall(data.ts)

summary(coal.data.decomp)

# Generate time series (trend test needs ts, not data.frame)
f_month <- month(first(wind_data_clean$DATE))
f_year <- year(first(wind_data_clean$DATE))
wind_data_ts <- ts(wind_data_clean$AWND.clean,
                   start=c(f_year,f_month),
                   frequency=12) 

#decompose
wind_data_decomp <- stl(wind_data_ts,s.window = "periodic")
plot(wind_data_decomp)

# Run SMK test
wind_data_trend1 <- Kendall::SeasonalMannKendall(wind_data_ts)

# Inspect results
wind_data_trend1
summary(wind_data_trend1)


wind_data_trend2 <- trend::smk.test(wind_data_ts)
# Inspect results
wind_data_trend2
summary(wind_data_trend2)

#Visualization
wind_data_plot <-
ggplot(wind_data, aes(x = DATE, y = AWND)) +
  geom_point() +
  geom_line() +
  ylab("Average Wind Speed") +
  geom_smooth( method = lm )
print(wind_data_plot)


df2 <- df[,-2]
```



#Linear Regression 

```{r}

schuylkill.data <-full.data %>% 
  filter(County == "Schuylkill") %>%
  select(coal.prod.by.year, Health.Outcomes.Z.Score, Health.Factors.Z.Score, perc.bachdegree, perc.white, medage, medincome)


```

#run MLR
```{r}

schuylkill.coal.health.regression2 <- lm(data = schuylkill.data, Health.Factors.Z.Score ~ coal.prod.by.year)

summary(schuylkill.coal.health.regression2)

schuylkill.coal.health.regression3 <- lm(data = schuylkill.data, Health.Outcomes.Z.Score ~ coal.prod.by.year)

summary(schuylkill.coal.health.regression3)

```

#Check MLR assumptions
```{r}

par(mfrow = c(2,2), mar=c(4,4,4,4))
plot(acs.coal.health.regression)
par(mfrow = c(1,1))

acs.health.coal.Corr <- cor(data.coal.health.acs)
corrplot(PeterPaulCorr, method = "ellipse")
corrplot.mixed(PeterPaulCorr, upper = "ellipse")

#Choose a model by AIC in a Stepwise Algorithm
step(acs.coal.health.regression)



```


